import { mkdir, writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { createApp } from '../src/server.js';
import { launchBrowser } from '../src/pdf.js';
import { verifyAcquisition } from './verify-acquisition.mjs';
import { verifyMetaAds } from './verify-meta-ads.mjs';

const artifacts = new URL('../artifacts/validation/', import.meta.url);
await mkdir(artifacts, { recursive: true });
const app = createApp();
await new Promise(resolve => app.server.listen(0, '127.0.0.1', resolve));
const base = `http://127.0.0.1:${app.server.address().port}`;
let browser;
const checks = [];
const record = text => { checks.push(text); console.log('OK:', text); };
try {
  browser = await launchBrowser();
  const page = await browser.newPage({ viewport: { width: 1440, height: 1100 }, acceptDownloads: true });
  const pageErrors = [];
  page.on('pageerror', error => pageErrors.push(error.message));
  await page.goto(base + '/nova-proposta');
  await page.waitForFunction(() => !document.querySelector('#preview-button').disabled);
  await page.screenshot({ path: new URL('desktop-empty.png', artifacts).pathname.replace(/^\/(\w:)/, '$1'), fullPage: true });
  await page.getByRole('button', { name: 'Visualizar proposta' }).click();
  assert.equal(await page.locator('[aria-invalid="true"]').count(), 4);
  assert.equal(await page.locator('#productId').evaluate(el => el === document.activeElement), true);
  record('Validação dos quatro campos e foco no primeiro erro.');
  await page.locator('#productId').selectOption('google-ads');
  await page.locator('#clientName').fill('Dra. Daniela');
  await page.locator('#price').fill('1000');
  await page.locator('#paymentTerms').fill('Pagamento antecipado, no momento de início dos serviços.');
  assert.equal((await page.locator('#price').inputValue()).replace(/\s/g, ' '), 'R$ 1.000,00');
  const generatedResponse = page.waitForResponse(response => response.url().endsWith('/api/proposals'));
  await page.getByRole('button', { name: 'Visualizar proposta' }).click();
  const generated = await (await generatedResponse).json();
  await page.waitForFunction(() => !document.querySelector('#download-button').disabled);
  const frame = page.frameLocator('#proposal-preview');
  assert.equal(await frame.locator('.client-name').textContent(), 'Dra. Daniela');
  assert.equal(await frame.locator('.payment-terms').textContent(), 'Pagamento antecipado, no momento de início dos serviços.');
  assert.equal((await frame.locator('.price').textContent()).replace(/\s/g, ' '), 'R$ 1.000,00');
  const downloadEvent = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Baixar PDF' }).click();
  const download = await downloadEvent;
  assert.equal(download.suggestedFilename(), 'Proposta-Google-Ads-Dra-Daniela.pdf');
  const pdfPath = new URL(download.suggestedFilename(), artifacts);
  await download.saveAs(pdfPath.pathname.replace(/^\/(\w:)/, '$1'));
  const { readFile } = await import('node:fs/promises');
  assert.deepEqual(await readFile(pdfPath), Buffer.from(generated.pdf, 'base64'));
  await writeFile(new URL('preview.html', artifacts), generated.html);
  await page.screenshot({ path: new URL('desktop-preview.png', artifacts).pathname.replace(/^\/(\w:)/, '$1'), fullPage: true });
  record('Dra. Daniela: prévia conferida e download idêntico ao PDF da geração.');
  const overflow = await frame.locator('.content').evaluateAll(nodes => nodes.some(el => el.scrollHeight > el.clientHeight || el.scrollWidth > el.clientWidth + 1));
  assert.equal(overflow, false);
  record('Páginas sem conteúdo fora dos limites.');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: new URL('mobile-preview.png', artifacts).pathname.replace(/^\/(\w:)/, '$1'), fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  record('Interface mobile de 390 px sem rolagem horizontal.');
  await page.getByRole('button', { name: 'Ampliar' }).click();
  assert.equal(await page.locator('#zoom-button').getAttribute('aria-pressed'), 'true');
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.getByRole('button', { name: 'Ajustar' }).click();
  record('Ampliação da prévia no mobile sem alargar o formulário.');
  await page.locator('#clientName').fill('Dra. Maria Eduarda de Albuquerque e Vasconcelos — Clínica Integrada de Saúde e Especialidades Médicas '.repeat(3).slice(0, 300));
  assert.equal(await page.locator('#download-button').isDisabled(), true);
  assert.equal(await page.locator('#empty-preview').isVisible(), true);
  const longResponse = page.waitForResponse(response => response.url().endsWith('/api/proposals'));
  await page.getByRole('button', { name: 'Visualizar proposta' }).click();
  const long = await (await longResponse).json();
  assert.ok(long.pdf, long.message);
  await writeFile(new URL('Proposta-Google-Ads-Nome-Longo.pdf', artifacts), Buffer.from(long.pdf, 'base64'));
  await page.waitForFunction(() => !document.querySelector('#download-button').disabled);
  assert.equal(await frame.locator('.content').evaluateAll(nodes => nodes.some(el => el.scrollWidth > el.clientWidth + 1 || el.scrollHeight > el.clientHeight)), false);
  await page.screenshot({ path: new URL('mobile-long-name.png', artifacts).pathname.replace(/^\/(\w:)/, '$1'), fullPage: true });
  record('Nome de 300 caracteres preservado sem overflow; edição invalida o download anterior.');
  const raw = { productId: 'google-ads', clientName: '<script>alert("teste")</script>' + 'X'.repeat(250), price: '999.999.999,99', paymentTerms: ('Pagamento em parcelas conforme acordado.\n').repeat(100).slice(0, 4000) };
  const edgeResponse = await fetch(base + '/api/proposals', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(raw) });
  const edge = await edgeResponse.json();
  assert.equal(edgeResponse.status, 200, edge.message);
  await writeFile(new URL('Proposta-Google-Ads-Texto-Extenso.pdf', artifacts), Buffer.from(edge.pdf, 'base64'));
  const edgePage = await browser.newPage();
  await edgePage.setContent(edge.html);
  assert.equal(await edgePage.locator('script').count(), 0);
  assert.equal(await edgePage.locator('.client-name').textContent(), raw.clientName);
  assert.equal(await edgePage.locator('.content').evaluateAll(nodes => nodes.some(el => el.scrollWidth > el.clientWidth + 1 || el.scrollHeight > el.clientHeight)), false);
  assert.equal((await edgePage.locator('.payment-terms').allTextContents()).join(''), raw.paymentTerms.trim());
  record('Injeção exibida como texto; nome sem espaços, valor máximo e pagamento extenso paginados sem perda.');
  await page.route('**/api/proposals', route => route.fulfill({ status: 500, contentType: 'application/json', body: JSON.stringify({ message: 'Não foi possível gerar o PDF. Tente novamente.' }) }));
  await page.locator('#clientName').fill('Teste falha');
  await page.getByRole('button', { name: 'Visualizar proposta' }).click();
  await page.locator('#global-error').waitFor({ state: 'visible' });
  assert.equal(await page.locator('#download-button').isDisabled(), true);
  record('Erro de geração visível e download bloqueado.');
  await page.unroute('**/api/proposals');
  await page.route('**/api/proposals', async route => {
    await new Promise(resolve => setTimeout(resolve, 700));
    await route.fulfill({ contentType: 'application/json', body: JSON.stringify(generated) });
  });
  await page.getByRole('button', { name: 'Visualizar proposta' }).click();
  assert.equal(await page.locator('#preview-button').isDisabled(), true);
  await page.locator('#clientName').fill('Edição durante a geração');
  await page.waitForTimeout(900);
  assert.equal(await page.locator('#download-button').isDisabled(), true);
  record('Estado de carregamento e resposta obsoleta descartada após editar durante a geração.');
  const acquisition = await verifyAcquisition({ page, artifacts, record });
  const metaAds = await verifyMetaAds({ page, artifacts, record });
  assert.deepEqual(pageErrors, []);
  record('Nenhum erro JavaScript no navegador.');
  await writeFile(new URL('results.json', artifacts), JSON.stringify({ checks, generatedPages: generated.pageCount, longNamePages: long.pageCount, extensiveTextPages: edge.pageCount, acquisition, metaAds }, null, 2));
} finally { await browser?.close(); await app.close(); }
